# Generated by Django 5.2.1 on 2025-05-13 12:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.TextField(verbose_name='Description du scénario')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Scénario',
                'verbose_name_plural': 'Scénarios',
            },
        ),
        migrations.CreateModel(
            name='JoueurState',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faim', models.IntegerField(default=100, verbose_name='Niveau de faim')),
                ('energie', models.IntegerField(default=100, verbose_name="Niveau d'énergie")),
                ('moral', models.IntegerField(default=100, verbose_name='Niveau de moral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Joueur')),
                ('scenario_actuel', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='survie.scenario', verbose_name='Scénario actuel')),
            ],
            options={
                'verbose_name': 'État du joueur',
                'verbose_name_plural': 'États des joueurs',
            },
        ),
        migrations.CreateModel(
            name='Choix',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texte', models.CharField(max_length=200, verbose_name='Description du choix')),
                ('delta_faim', models.IntegerField(default=0, verbose_name='Impact sur la faim')),
                ('delta_energie', models.IntegerField(default=0, verbose_name="Impact sur l'énergie")),
                ('delta_moral', models.IntegerField(default=0, verbose_name='Impact sur le moral')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='choix', to='survie.scenario', verbose_name='Scénario associé')),
                ('scenario_suivant', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='choix_menant_ici', to='survie.scenario', verbose_name='Scénario suivant')),
            ],
            options={
                'verbose_name': 'Choix',
                'verbose_name_plural': 'Choix',
            },
        ),
    ]
