# Generated by Django 5.2.1 on 2025-05-13 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('survie', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='choix',
            name='ajoute_objet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name="Objet ajouté à l'inventaire"),
        ),
        migrations.AddField(
            model_name='choix',
            name='requiert_objet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objet requis pour ce choix'),
        ),
        migrations.AddField(
            model_name='joueurstate',
            name='inventaire',
            field=models.JSONField(blank=True, default=list, verbose_name='Inventaire du joueur'),
        ),
        migrations.AddField(
            model_name='joueurstate',
            name='progression',
            field=models.IntegerField(default=0, verbose_name="Progression dans l'histoire (0-100)"),
        ),
        migrations.AddField(
            model_name='joueurstate',
            name='scenarios_visites',
            field=models.JSONField(blank=True, default=list, verbose_name='Scénarios déjà visités'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='est_debut',
            field=models.BooleanField(default=False, verbose_name='Est le scénario de début'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='est_fin',
            field=models.BooleanField(default=False, verbose_name='Est un scénario de fin'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='requiert_objet',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Objet requis pour ce scénario'),
        ),
    ]
